FROM ros:kinetic-desktop-full-3-programming

RUN apt update 

# System Utilities
RUN apt install -y python-catkin-tools			# More modern build tools that replace catkin_make
RUN apt install -y ros-kinetic-rqt-launchtree		# Displays launchfiles
